import { Platform, StatusBar, StyleSheet } from "react-native";
import { COLORS } from "../../constants/color";
import { FONTS } from "../../constants/font";
import { hp, wp } from "../../utils/responsive-helper";

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: COLORS.White,
  },
  CardContainer: {
    backgroundColor: COLORS.White,
    flex: 1,
  },
  ShortCutComponentsRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginTop: hp(27),
    width: wp(327),
  },
  welcomeText: {
    marginTop: hp(25),
    alignItems: "flex-start",
    marginLeft: wp(25),
    fontSize: wp(25),
  },
  empData: {
    marginTop: hp(25),
    fontSize: wp(14),
    // fontWeight: 'normal',
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Bold,
    // fontStyle: 'normal',
  },
  welcomeTop: {
    marginTop: hp(4),
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Semibold,
    fontStyle: "normal",
  },
  signInName: {
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Bold,
    fontStyle: "normal",
  },
  welcome: {
    marginTop: hp(25),
    fontSize: wp(14),
    fontWeight: "500",
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Semibold,
    // fontStyle: 'normal',
  },
  shortcutHeading: {
    marginTop: hp(25),
    marginLeft: wp(24),
    fontSize: wp(16),
    // fontWeight: 'normal',
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Bold,
    // fontStyle: 'normal',
  },
  facility: {
    marginTop: hp(12),
    fontSize: wp(14),
    fontWeight: "500",
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Semibold,
    // fontStyle: 'normal',
  },
  empfacility: {
    marginTop: hp(12),
    fontSize: wp(14),
    // fontWeight: '600',
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Bold,
    //fontStyle: 'normal',
  },

  idText: {
    fontSize: wp(14),
    fontWeight: "500",
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Semibold,
    //fontStyle: 'normal',
    marginLeft: wp(16),
    marginTop: hp(7),
    marginBottom: hp(7),
  },
  entry_label: {
    fontSize: wp(18),
    // fontWeight: 'normal',
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Semibold,
    // fontStyle: 'normal',
    paddingLeft: wp(6),
  },
  shortcutLayout: {
    marginTop: hp(28),
    width: wp(327),
    marginLeft: wp(24),
    marginRight: wp(24),
    // height: hp(224),
    borderRadius: wp(15),
    borderTopRightRadius: wp(20),
    backgroundColor: COLORS.GreyAccent,
  },
  digitalId: {
    flexDirection: "column",
    //fontWeight: 'bold',
  },
  drawerComponentsRow: {
    flexDirection: "row",
    // justifyContent: "space-evenly",
    // width: wp(46),
    borderRadius: wp(8),
    // marginLeft: wp(42),
    // marginRight: wp(54),
  },
  idcard: {
    flexWrap: "wrap",
    position: "relative",
    marginLeft: wp(16),
  },
  idcard_bg: {
    flexDirection: "row",
    width: wp(321),
    height: hp(44),
    margin: wp(2),
    alignItems: "center",
    borderTopRightRadius: wp(8),
    borderTopLeftRadius: wp(8),
    backgroundColor: COLORS.White,
  },
  qrcode: {
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "space-between",
    width: wp(321),
  },
  qrimage: {
    alignItems: "center",
    justifyContent: "center",
    width: wp(74),
    height: wp(74),
    backgroundColor: COLORS.White,
    borderRadius: wp(6),
    marginTop: hp(10),
    marginRight: hp(16),
  },
  profileImage: {
    width: wp(30),
    height: hp(20),
    marginLeft: wp(10),
    alignItems: "center",
  },
  componentImageBackground: {
    height: hp(46),
    width: wp(46),
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: COLORS.White,
    borderRadius: wp(8),
  },
  componentImage: {
    width: wp(30),
    height: wp(30),
    paddingRight: wp(10),
  },
  componentTitle: {
    // top: hp(7),
    fontSize: wp(12),
    color: COLORS.Black,
    textAlign: "center",
    paddingBottom: wp(7),
    fontFamily: FONTS.Urbanist_Semibold,
    flexWrap: "wrap",
    width: wp(96),
    // marginLeft: wp(18),
    marginTop: hp(12),
  },
  buttonStyle: {
    padding: wp(15),
    width: wp(320),
    height: hp(60),
    alignSelf: "center",
    marginTop: hp(36),
    marginBottom: hp(32),
    borderRadius: wp(18),
    backgroundColor: COLORS.Purple,
  },
  buttonTxt: {
    fontSize: wp(20),
    alignItems: "center",
    textAlign: "center",
    color: COLORS.White,
    fontFamily: FONTS.Urbanist,
  },
  componentVerification: {
    left: wp(12),
    width: wp(20),
    height: wp(20),
    top: wp(15),
    alignContent: "flex-end",
    marginLeft: wp(70),
    marginTop: wp(-25),
    zIndex: wp(1),
  },
  containerborder: {
    padding: wp(20),
    flex: 1,
    backgroundColor: COLORS.White,
    paddingTop: Platform.OS === "android" ? StatusBar.currentHeight : 0,
  },
  TextContainer: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: hp(50),
  },

  RadioContainer: {
    borderWidth: 1,
    borderColor: COLORS.LightBlue,
    borderRadius: wp(8),
    marginLeft: wp(24),
    marginRight: wp(20),
    marginTop: hp(29),
    padding: 0,
    // flexWrap: 'wrap',
    width: wp(327),
    height: hp(191),
    backgroundColor: COLORS.LightBlue,
  },
  divider: {
    backgroundColor: COLORS.White,
    height: hp(1),
    width: wp(295),
    marginTop: hp(0),
    marginLeft: wp(14),
    marginRight: wp(16),
  },
});

export default styles;
