import { StyleSheet } from "react-native";
import { COLORS } from "../../../constants/color";
import { FONTS } from "../../../constants/font";
import { hp, wp } from "../../../utils/responsive-helper";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.White,
  },
  icons: {
    width: wp(22),
    height: hp(22),
    resizeMode: "contain",
  },
  verificationHistoryRow: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginTop: hp(10),
    marginBottom: hp(10),
    marginLeft: wp(5),
  },
  verificationHistoryRowEmployee: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginTop: hp(5),
    marginBottom: hp(5),
    marginLeft: wp(5),
  },
  verificationHistory: {
    fontSize: hp(22),
    fontWeight: "700",
    fontFamily: FONTS.Urbanist_Semibold,
    color: COLORS.GrayDark,
    marginLeft: wp(24),
  },
  verificationCard: {
    margin: wp(10),
    padding: wp(5),
    borderRadius: wp(10),
    marginTop: hp(20),
    marginLeft: wp(24),
    marginRight: wp(24),
  },
  verificationCardData: {
    marginLeft: wp(5),
    marginTop: hp(1),
    color: COLORS.White,
    fontSize: hp(16),
    fontWeight: "600",
    fontFamily: FONTS.Urbanist_Bold,
  },
  verificationCardLabel: {
    marginLeft: wp(5),
    marginTop: hp(1),
    color: COLORS.White,
    fontSize: hp(16),
    fontWeight: "500",
    fontFamily: FONTS.Urbanist,
  },
  addressCard: {
    marginLeft: wp(24),
    marginRight: wp(24),
    borderWidth: 1,
    borderRadius: wp(17),
    borderColor: COLORS.LightGrey,
  },
  address: {
    flexDirection: "row",
    justifyContent: "space-between",
    margin: wp(6),
    padding: hp(4),
  },
  addressTitle: {
    paddingTop: hp(18),
    fontSize: hp(18),
    marginLeft: wp(10),
    marginBottom: hp(10),
    fontFamily: FONTS.Urbanist_Bold,
    color: COLORS.DarkGrey,
    alignSelf: "flex-start",
  },
  addressContent: {
    color: COLORS.DarkGrey,
    fontSize: hp(16),
    fontFamily: FONTS.Urbanist_Medium,
    flexWrap: "wrap",
    alignSelf: "flex-start",
    fontWeight: "500",
  },
  addressContentRight: {
    color: COLORS.DarkGrey,
    fontSize: hp(16),
    fontFamily: FONTS.Urbanist_Semibold,
    flexWrap: "wrap",
    alignSelf: "flex-start",
    width: wp(130),
    marginLeft: wp(20),
    textAlign: "right",
    fontWeight: "600",
  },
  buttonProceed: {
    backgroundColor: COLORS.Blue,
    borderRadius: wp(10),
    margin: wp(10),
    width: wp(157),
    height: hp(57),
    justifyContent: "center",
  },
  textProceed: {
    color: COLORS.White,
    alignSelf: "center",
    fontSize: hp(18),
    fontWeight: "700",
    fontFamily: FONTS.Urbanist_Bold,
  },
  buttonBack1: {
    backgroundColor: COLORS.Blue,
    padding: wp(12),
    borderRadius: wp(10),
    marginHorizontal: wp(25),
    width: wp(327),
    marginTop: hp(22),
  },
  textBack1: {
    color: COLORS.White,
    alignSelf: "center",
    fontSize: hp(18),
    fontWeight: "700",
    fontFamily: FONTS.Urbanist_Bold,
  },
  textBack0: {
    color: COLORS.GrayDark,
    textAlign: "center",
    fontSize: hp(18),
    fontFamily: FONTS.Urbanist_Bold,
  },
  buttonBack0: {
    borderRadius: wp(10),
    margin: wp(10),
    width: wp(157),
    height: hp(57),
    borderColor: COLORS.Blue,
    borderWidth: wp(1),
    justifyContent: "center",
  },
  buttonsRow: {
    flexDirection: "row",
    justifyContent: "space-evenly",
    marginLeft: wp(24),
    marginRight: wp(24),
  },
  viewContainer: {
    marginBottom: hp(10),
    backgroundColor: COLORS.White,
  },
  header: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginTop: hp(26),
    marginBottom: hp(10),
    alignItems: "center",
    height: hp(40),
  },
  back: {
    backgroundColor: COLORS.LightGrey,
    width: wp(44),
    height: wp(44),
    borderColor: COLORS.LightGrey,
    borderRadius: wp(30),
    alignItems: "center",
    justifyContent: "center",
    marginLeft: hp(24),
  },
  backButton: {
    width: wp(25),
    height: wp(25),
    tintColor: COLORS.DarkGrey,
  },
  headerTitle: {
    fontSize: hp(24),
    marginLeft: hp(18),
    fontFamily: FONTS.Urbanist_Bold,
    color: COLORS.DarkGrey,
    alignItems: "center",
  },
  contactNumber: {
    marginTop: hp(6),
    borderBottomColor: COLORS.LightGrey,
    borderBottomWidth: wp(1),
    marginHorizontal: wp(10),
  },
});

export default styles;
