import { StyleSheet } from "react-native";
import { COLORS } from "../../constants/color";
import { FONTS } from "../../constants/font";

import { hp, wp } from "../../utils/responsive-helper";

const styles = StyleSheet.create({
  safeareaView: {
    flex: 1,
    backgroundColor: COLORS.White,
  },
  header: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginLeft: hp(24),
    marginTop: hp(26),
    marginBottom: hp(26),
    alignItems: "center",
    height: hp(40),
  },
  back: {
    backgroundColor: COLORS.LightGrey,
    width: wp(44),
    height: wp(44),
    borderColor: COLORS.LightGrey,
    borderRadius: wp(30),
    alignItems: "center",
    justifyContent: "center",
  },
  backButton: {
    width: wp(25),
    height: wp(25),
    tintColor: COLORS.DarkGrey,
  },
  headerTitle: {
    fontSize: hp(24),
    marginLeft: hp(18),
    fontFamily: FONTS.Urbanist_Bold,
    color: COLORS.DarkGrey,
    alignItems: "center",
  },
  nodataStyle: {
    textAlignVertical: "center",
    textAlign: "center",
    fontSize: hp(17),
    fontFamily: FONTS.Urbanist,
    fontWeight: "700",
    color: COLORS.DarkGrey,
    marginBottom: hp(30),
  },
  nodataViewStyle: {
    justifyContent: "center",
    alignContent: "center",
    marginTop: hp(10),
  },
  calendarView: {
    width: wp(300),
    height: hp(50),
    borderRadius: hp(22),
    borderWidth: wp(1),
    borderColor: COLORS.Blue,
    justifyContent: "flex-start",
    alignItems: "center",
    alignSelf: "center",
    flexDirection: "row",
  },
  calendarIcon: {
    marginLeft: wp(30),
  },
  requiredIcon: {
    marginLeft: wp(24),
  },
  requiredIcon1: {
    marginLeft: wp(6),
    width: wp(113),
    textAlign: "center",
    marginBottom: hp(5),
    color: COLORS.Black,
    alignSelf: "center",
    fontSize: hp(12),
    fontFamily: FONTS.Urbanist_Medium,
  },
  mainCalendarView: {
    marginTop: hp(20),
    justifyContent: "center",
    alignItems: "center",
  },
  tabcolorStyle: {
    width: wp(186),
    height: hp(50),
    borderRadius: wp(10),
    borderWidth: hp(1),
    borderColor: COLORS.LightGrey,
  },
  attendanceViewStyle: {
    borderColor: COLORS.LightGrey,
    borderRadius: wp(15),
    width: wp(327),
    height: hp(60),
  },
  attendanceTextStyle: {
    justifyContent: "center",
    alignItems: "center",
    width: wp(65),
  },
  textstyleView: {
    color: COLORS.Black,
    alignSelf: "flex-start",
    fontSize: hp(16),
    fontFamily: FONTS.Urbanist_Semibold,
    textAlign: "center",
    marginTop: hp(20),
  },
  clockinclockoutView: {
    width: wp(113),
    height: hp(18),
    marginBottom: hp(2),
    color: COLORS.Black,
    alignSelf: "center",
    fontSize: hp(12),
    fontFamily: FONTS.Urbanist_Medium,
    textAlign: "center",
  },
  clockinclockOutViewSytle: {
    flexDirection: "column",
    marginLeft: wp(10),
    marginRight: wp(10),
    marginTop: hp(10),
    justifyContent: "flex-start",
    // alignItems: 'center',
    width: wp(152),
  },
  totalTimeView: {
    width: wp(55),
    marginTop: hp(20),
    color: COLORS.Black,
    alignSelf: "flex-start",
    fontSize: hp(16),
    fontFamily: FONTS.Urbanist_Semibold,
    textAlign: "center",
  },
  messageView: {
    marginTop: hp(14),
    marginLeft: wp(6),
    width: wp(28),
    height: hp(28),
    borderRadius: hp(5),
    backgroundColor: COLORS.LightGrey,
    justifyContent: "center",
    alignItems: "center",
  },
  clockdistanceStyle: {
    marginTop: hp(2),
    fontSize: hp(18),
    color: COLORS.Red,
    fontFamily: FONTS.Urbanist_Semibold,
  },
  attendanceTabContainer: {
    flexDirection: "row",
    borderColor: COLORS.LightGrey,
    borderWidth: 1,
    borderRadius: hp(10),
    width: wp(327),
  },
  attendanceTab: {
    width: wp(160),
    height: hp(47),
    borderColor: COLORS.LightGrey,
    // borderWidth: 1,
    borderRadius: hp(10),
    marginLeft: hp(0),
    marginRight: hp(0),
    justifyContent: "center",
    alignItems: "center",
  },
  attendanceTabView: {
    width: wp(160),
    height: hp(50),
    alignItems: "center",
    justifyContent: "center",
  },
  attendanceTabText: {
    fontSize: hp(18),
    textAlign: "center",
    fontFamily: FONTS.Urbanist_Semibold,
  },
  attendanceListRow: {
    width: wp(327),
    height: hp(50),
  },
  attendanceListCard: {
    flexDirection: "row",
    justifyContent: "flex-start",
    width: wp(322),
  },
  calendarText: {
    fontSize: hp(16),
    fontFamily: FONTS.Urbanist_Semibold,
    fontWeight: "600",
    marginLeft: wp(15),
    marginRight: wp(37),
  },
});

export default styles;
