
default_platform(:ios)
  
platform :ios do

desc "Description of IOS Application"
lane :build do |options|
filename = options[:parameter1]
desc "#{filename}"

buildenv = options[:buildenv] 
deploypath = "/Users/devops/.jenkins/jobs/entryPass_reactnative_ios_dev/workspace/ios/builds/EntryPass_react_native_0.0.#{filename}-release.ipa"
uploadfolder = "1K7rtfQE99SssGbvU5-hFNVU9jj6iIiHc"

  if buildenv == "qa"
        deploypath = "/Users/devops/.jenkins/jobs/entryPass_reactnative_ios_qa/workspace/ios/builds/EntryPass_react_native_0.0.#{filename}-release.ipa"
        uploadfolder = "10FA4dcwPKhRc0Dn-0jmpyQLqXFx3fh4O"
  end
    
    if buildenv == "uat"
       deploypath = "/Users/devops/.jenkins/jobs/entryPass_reactnative_ios_uat/workspace/ios/builds/EntryPass_react_native_0.0.#{filename}-release.ipa"
       uploadfolder = "1b9u7UUo-LT3cJfOwaqqF428_cxbowFBe"
    end



build_app(scheme: "Entry_Pass",
export_method: "ad-hoc",
 output_directory: "builds",output_name: "EntryPass_react_native_0.0.#{filename}-release.ipa")

upload_to_google_drive(
    drive_keyfile: '/Users/devops/Desktop/Google_drive/google-drive.json',
    service_account: true,
    folder_id: "#{uploadfolder}",
    upload_files: ["#{deploypath}"]
         )
end


  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end
end