import { StyleSheet, Dimensions } from "react-native";
const { width, height } = Dimensions.get("window");
import { COLORS } from "../constants/color";
import { FONTS } from "../constants/font";
import { wp, hp } from "../utils/responsive-helper";

const appHeaderStyles = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginLeft: width / 18,
    marginTop: hp(10),
  },
  back: {
    backgroundColor: COLORS.LightGrey,
    padding: hp(10),
    borderColor: COLORS.LightGrey,
    borderRadius: hp(30),
  },
  backButton: {
    width: wp(25),
    height: hp(25),
    tintColor: COLORS.DarkGrey,
  },
  headerTitle: {
    fontSize: hp(24),
    fontFamily: FONTS.Urbanist,
    fontWeight: "bold",
    color: COLORS.DarkGrey,
    marginLeft: width / 18,
  },
  RadioContainer: {
    borderWidth: 1,
    borderRadius: wp(8),
    // marginLeft: wp(10),
    // marginRight: wp(10),
    marginTop: hp(24),
    padding: hp(0),
    borderColor: "#D4D4D4",
    borderRadius: wp(22),
    backgroundColor: COLORS.White,
  },
  idText: {
    fontSize: wp(14),
    fontWeight: "normal",
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist,
    fontStyle: "normal",
    marginLeft: wp(16),
    marginTop: hp(7),
    marginBottom: hp(7),
  },
  idcard_bg: {
    flexDirection: "row",
    margin: wp(2),
    alignItems: "center",
    borderTopRightRadius: wp(8),
    borderTopLeftRadius: wp(8),
    backgroundColor: COLORS.White,
  },
  idcard_bg_cont: {
    flexDirection: "row",
    margin: wp(2),
    alignItems: "center",
    borderTopRightRadius: wp(22),
    borderTopLeftRadius: wp(22),
    backgroundColor: COLORS.White,
    justifyContent: "center",
    // marginLeft: hp(20),
    // alignItems: 'center',
  },
  buttonTxt: {
    fontSize: wp(18),
    alignItems: "center",
    textAlign: "center",
    color: COLORS.Black,
    fontFamily: FONTS.Urbanist,
    paddingTop: hp(5),
  },
});

const attendance_styles = StyleSheet.create({
  buttomContainer: {
    position: "relative",
    alignItems: "stretch",
    marginTop: hp(35),
    backgroundColor: COLORS.White,
  },
  photo: {
    height: hp(100),
    width: wp(80),
    alignItems: "center",
    justifyContent: "center",
    // position: "absolute",
    borderRadius: wp(10),
    marginLeft: hp(5),
    borderColor: COLORS.LightGrey,
  },
  clockoutin: {
    // marginTop: hp(2),
    alignSelf: "center",
    fontSize: hp(18),
    color: COLORS.Green,
    fontFamily: FONTS.Urbanist,
  },
  tabContainer: {
    height: hp(50),
    borderWidth: wp(1),
    borderColor: "transparent",
    borderTopLeftRadius: wp(10),
    borderTopRightRadius: wp(10),
  },
  tabBar: {
    height: hp(52),
    marginTop: hp(-14),
    width: wp(175),
    textAlign: "center",
    paddingHorizontal: wp(10),
    padding: wp(5),
    paddingVertical: hp(0),
  },
  tabBarTitle: {
    fontSize: hp(18),
    textAlign: "center",
    marginTop: hp(10),
    fontWeight: "600",
  },
  buttonStyleRedBG: {
    padding: hp(5),
    width: wp(220),
    height: hp(54),
    alignSelf: "center",
    backgroundColor: COLORS.Red,
    borderRadius: hp(8),
  },
  buttonStyleDisable: {
    padding: hp(5),
    width: wp(220),
    height: hp(54),
    alignSelf: "center",
    backgroundColor: COLORS.GrayLight,
    borderRadius: hp(8),
  },
  textStyle: {
    fontSize: hp(18),
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Medium,
    flex: 1,
  },
  textStyletime: {
    fontSize: wp(16),
    color: COLORS.DarkGrey,
    flex: 1,
    textAlign: "left",
    alignContent: "flex-start",
    marginLeft: hp(5),
    fontFamily: FONTS.Urbanist_Semibold,
  },
  textStyleHeading: {
    fontSize: hp(18),
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Bold,
    // fontWeight: '600',
    flex: 1,
    marginLeft: wp(10),
  },
  textStyleHeadingHistory: {
    fontSize: hp(18),
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Bold,
    flex: 1,
    marginBottom: wp(20),
  },
  shiftTimingText: {
    fontSize: hp(16),
    color: COLORS.DarkGrey,
    // marginLeft: wp(8),
    marginTop: hp(7),
    marginBottom: hp(7),
    alignSelf: "center",
    textAlign: "center",
    width: wp(128),
    height: hp(40),
  },
  shiftBackground: {
    backgroundColor: COLORS.LightBlue,
    borderWidth: wp(1),
    borderRadius: wp(21),
    borderTopLeftRadius: wp(0),
    borderTopRightRadius: wp(0),
    borderColor: COLORS.LightBlue,
    alignItems: "center",
  },
  empDetails: {
    fontSize: wp(16),
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist,
  },
  buttonTxt: {
    fontSize: wp(18),
    alignItems: "center",
    textAlign: "center",
    color: COLORS.Black,
    fontFamily: FONTS.Urbanist_Bold,
    alignSelf: "center",
    //marginTop:hp(12),
  },
  buttonTxt1: {
    fontSize: wp(18),
    // alignItems: 'center',
    textAlign: "center",
    color: COLORS.White,
    fontFamily: FONTS.Urbanist_Bold,
    // alignSelf:'center'
    marginTop: hp(12),
  },
  buttonTxtclockout: {
    marginTop: hp(5),
    fontSize: hp(18),
    alignItems: "center",
    textAlign: "center",
    color: COLORS.White,
    fontFamily: FONTS.Urbanist_Bold,
    paddingTop: hp(5),
  },
  progressLayout: {
    alignItems: "center",
    marginTop: hp(24),
  },
  idcard: {
    flex: 1,
    alignItems: "flex-start",
    marginLeft: wp(10),
  },
  welcome: {
    marginTop: hp(25),
    fontSize: wp(14),
    fontWeight: "normal",
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist,
    fontStyle: "normal",
  },
  facility: {
    marginTop: hp(12),
    fontSize: wp(14),
    fontWeight: "normal",
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist,
    fontStyle: "normal",
  },
  qrcode: {
    flexDirection: "row",
    alignSelf: "center",
    justifyContent: "space-between",
    width: wp(321),
    borderTopRightRadius: wp(22),
    borderTopLeftRadius: wp(22),
  },
  qrimage: {
    alignItems: "center",
    justifyContent: "center",
    width: wp(80),
    height: hp(100),
    backgroundColor: COLORS.White,
    borderRadius: wp(10),
    marginBottom: hp(10),
    marginLeft: hp(30),
  },
  divider: {
    backgroundColor: COLORS.LightGrey,
    height: hp(1),
    width: wp(327),
    marginTop: hp(0),
    marginLeft: wp(16),
    marginRight: wp(16),
  },
  divider_cont: {
    backgroundColor: COLORS.LightGrey,
    height: hp(1),
    width: wp(300),
    marginTop: hp(0),
    marginLeft: wp(16),
    marginRight: wp(16),
    // marginTop: hp(10),
    // marginBottom: hp(10),
  },
  buttonStyle: {
    width: wp(220),
    height: hp(54),
    // textAlign: 'center',
    alignSelf: "center",
    backgroundColor: COLORS.Yellow,
    borderRadius: wp(8),
    justifyContent: "center",
  },
  buttonStyle1: {
    width: wp(326),
    height: hp(54),
    alignSelf: "center",
    backgroundColor: COLORS.Yellow,
    borderRadius: hp(8),
    marginTop: wp(20),
    justifyContent: "center",
  },
});

const profilepage_styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    justifyContent: "flex-start",
    marginLeft: width / 18,
    marginTop: hp(10),
  },
  back: {
    backgroundColor: COLORS.LightGrey,
    padding: 10,
    borderColor: COLORS.LightGrey,
    borderRadius: 30,
  },
  backButton: {
    width: wp(25),
    height: hp(25),
    tintColor: COLORS.DarkGrey,
  },
  headerTitle: {
    fontSize: hp(24),
    fontFamily: FONTS.Urbanist,
    fontWeight: "bold",
    color: COLORS.DarkGrey,
    marginLeft: width / 18,
  },
  imageStyle: {
    flex: 1,
    justifyContent: "center",
    marginLeft: width * 0.24,
    width: width / 2,
    height: height / 6,
  },

  rowcontainer: {
    borderWidth: hp(1),
    borderColor: "#D4D4D4",
    borderRadius: wp(15),
    marginTop: hp(5),
    // padding: hp(10),
    height: hp(61),
    width: wp(327),
    justifyContent: "center",
    backgroundColor: COLORS.White,
  },
  row: {
    flexDirection: "row",
  },

  rowContainer: {
    flexDirection: "row",
    flex: 1,
    marginTop: hp(24),
    marginBottom: hp(22),
    //marginLeft: hp(10),
  },

  logoutBtn: {
    flexDirection: "row",
    backgroundColor: COLORS.Red,
    borderRadius: wp(8),
    padding: hp(5),
    marginLeft: width * 0.05,
    marginRight: width * 0.05,
    marginTop: height * 0.007,
    alignItems: "center",
    justifyContent: "center",
  },
  logoutIcons: {
    alignItems: "center",
    resizeMode: "contain",
  },
  logoutText: {
    textAlignVertical: "center",
    fontSize: hp(18),
    fontFamily: FONTS.Urbanist,
    fontWeight: "bold",
    color: COLORS.White,
  },
  buttonStyle: {
    paddingTop: hp(5),
    width: wp(150),
    height: hp(40),
    alignSelf: "center",
    backgroundColor: COLORS.Yellow,
    borderRadius: wp(8),
  },
  buttonStyle1: {
    padding: hp(5),
    width: wp(302),
    height: hp(40),
    alignSelf: "center",
    backgroundColor: COLORS.Yellow,
    borderRadius: hp(8),
    marginTop: wp(20),
    marginBottom: wp(20),
  },
  buttonTxt: {
    fontSize: hp(16),
    alignItems: "center",
    textAlign: "center",
    color: COLORS.Black,
    fontFamily: FONTS.Urbanist,
    paddingTop: hp(5),
  },
  contButtonStyle: {
    marginLeft: wp(24),
    width: wp(326),
    height: hp(54),
    backgroundColor: COLORS.Blue,
    marginTop: hp(20),
    borderRadius: wp(10),
  },
  contButtonTxt: {
    fontSize: hp(18),
    marginTop: hp(16),
    alignSelf: "center",
    fontWeight: "700",
    color: COLORS.White,
    fontFamily: FONTS.Urbanist_Bold,
  },
  instructions: {
    fontSize: hp(16),
    fontWeight: "500",
    textAlign: "center",
    color: "#333333",
    marginBottom: hp(44),
    marginTop: hp(22),
    fontFamily: FONTS.Urbanist,
  },
  locationDetails: {
    fontSize: hp(18),
    textAlign: "left",
    color: "#262626",
    fontFamily: FONTS.Urbanist,
  },
  profileTitleRow: {
    flexDirection: "column",
    justifyContent: "space-evenly",
    marginBottom: hp(30),
    marginLeft: wp(15),
    marginRight: wp(15),
  },
  profileImage: {
    width: wp(21),
    height: hp(26),
  },
  locationContainer: {
    flexDirection: "row",
    marginLeft: wp(71),
  },
  container: {
    flex: 1,
    backgroundColor: "#FFFFFF",
    alignItems: "center",
    justifyContent: "center",
  },
  subContainer: {
    marginLeft: wp(2),
    borderColor: "black",
  },
  textStyle: {
    fontSize: wp(18),
    fontWeight: "normal",
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist,
    fontStyle: "normal",
    flex: 1,
  },
  textStyleRight: {
    fontSize: hp(18),
    fontWeight: "normal",
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist,
    // fontStyle: "normal",
    // flex: 1,
    // textAlign: "right",
    // marginLeft: hp(0),
  },
  textStyleLeft: {
    fontSize: hp(18),
    //fontWeight: '600',
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Semibold,
    // flex: 1,
    // textAlign: "left",
  },
  timertextStyle: {
    color: COLORS.DarkGrey,
    fontFamily: FONTS.Urbanist_Semibold,
    flex: 1,
    textAlign: "center",
    fontSize: hp(40),
    justifyContent: "center",
    marginBottom: hp(20),
    alignSelf: "center",
    width: wp(128),
    // backgroundColor: COLORS.Red,
  },
});
export { profilepage_styles, appHeaderStyles, attendance_styles };
